version: '3'
services:
  postgres:
    image: postgres:alpine3.16
    environment: [
      POSTGRES_USER=postgres,
      POSTGRES_PASSWORD=Ukasl23calEWLPPS,
      PGDATA=/var/lib/postgresql/data/pgdata,
      D:\\temp\\ecommerce:/var/lib/postgresql/data
    ]
    ports:
      - "5432:5432"

